const modules = [
  {id:'dashboard',icon:'▦',name:'Dashboard',group:'VISÃO GERAL'},
  {id:'pacientes',icon:'◉',name:'Pacientes',fields:['Nome completo','CPF','Telefone','E-mail']},
  {id:'psicologos',icon:'♙',name:'Psicólogos',fields:['Nome completo','CRP','Especialidade','Telefone']},
  {id:'funcionarios',icon:'♟',name:'Funcionários',fields:['Nome completo','Cargo','Telefone','E-mail']},
  {id:'perfis',icon:'◈',name:'Perfís e permissões',fields:['Perfil','Descrição','Permissões']},
  {id:'especialidades',icon:'◇',name:'Especialidades',fields:['Nome','Descrição']},
  {id:'convenios',icon:'◇',name:'Convênios',fields:['Nome','CNPJ','Contato']},
  {id:'salas',icon:'▣',name:'Salas',fields:['Nome','Número','Capacidade','Status']},
  {id:'agenda',icon:'◷',name:'Agenda profissional',fields:['Psicólogo','Data','Horário inicial','Horário final']},
  {id:'agendamentos',icon:'▣',name:'Agendamentos',fields:['Paciente','Psicólogo','Data','Horário','Status']},
  {id:'reagendamentos',icon:'↻',name:'Reagendamentos',fields:['Agendamento','Nova data','Novo horário','Motivo']},
  {id:'checkins',icon:'✓',name:'Check-in e presença',fields:['Paciente','Data','Horário','Situação']},
  {id:'prontuarios',icon:'▤',name:'Prontuários',fields:['Paciente','Data de nascimento','Contato de emergência','Observações']},
  {id:'evolucoes',icon:'✎',name:'Evoluções de sessão',fields:['Paciente','Psicólogo','Data','Registro da sessão']},
  {id:'recibos',icon:'▧',name:'Recibos',fields:['Paciente','Data','Valor (R$)','Descrição']},
  {id:'receitas',icon:'↑',name:'Receitas',fields:['Descrição','Data','Valor (R$)','Categoria']},
  {id:'despesas',icon:'↓',name:'Despesas',fields:['Descrição','Data','Valor (R$)','Categoria']},
  {id:'relatorio',icon:'▥',name:'Relatório financeiro',group:'FINANCEIRO'},
  {id:'produtos',icon:'◫',name:'Produtos e materiais',group:'SUPRIMENTOS',fields:['Produto','Categoria','Preço (R$)','Estoque mínimo']},
  {id:'estoque',icon:'▤',name:'Controle de estoque',fields:['Produto','Quantidade','Movimentação','Data']},
  {id:'compras',icon:'🛒',name:'Fornecedores e compras',fields:['Fornecedor','Produto','Quantidade','Valor (R$)']},
  {id:'indicadores',icon:'◒',name:'Indicadores',group:'ANÁLISES'}
];
const sample={
 pacientes:[['Mariana Costa','123.456.789-00','(11) 99999-1111','mariana@email.com'],['Lucas Almeida','987.654.321-00','(11) 98888-2222','lucas@email.com'],['Ana Clara Souza','456.789.123-00','(11) 97777-3333','ana@email.com']],
 psicologos:[['Dra. Juliana Martins','CRP 06/123456','Terapia Cognitiva','(11) 95555-5555'],['Dr. Rafael Lima','CRP 06/654321','Psicanálise','(11) 94444-4444']],
 agendamentos:[['Mariana Costa','Dra. Juliana Martins','2026-07-20','09:00','Confirmado'],['Lucas Almeida','Dr. Rafael Lima','2026-07-20','10:30','Pendente'],['Ana Clara Souza','Dra. Juliana Martins','2026-07-20','14:00','Confirmado']],
 receitas:[['Consulta particular','2026-07-05','450,00','Atendimentos'],['Convênio Vida','2026-07-12','1250,00','Convênios']],despesas:[['Aluguel','2026-07-03','1800,00','Fixa'],['Material de escritório','2026-07-11','180,00','Operacional']],
 produtos:[['Papel A4','Escritório','32,90','10'],['Álcool gel','Higiene','18,50','5']],estoque:[['Papel A4','18','Entrada','2026-07-10'],['Álcool gel','3','Saída','2026-07-17']]
};
let current='dashboard', editIndex=null;
function db(){return JSON.parse(localStorage.getItem('menteSerenaDB')||'{}')}
function save(data){localStorage.setItem('menteSerenaDB',JSON.stringify(data))}
function seed(force=false){if(!force&&localStorage.getItem('menteSerenaDB'))return;const d={};modules.forEach(m=>d[m.id]=sample[m.id]||[]);save(d)}
function label(m){return m.name.replace(' e ',' & ')}
function menu(){let last='';document.querySelector('#menu').innerHTML=modules.map(m=>{let g=m.group&&m.group!==last?`<div class="menu-label">${m.group}</div>`:'';last=m.group||last;return `${g}<button class="nav-item ${m.id===current?'active':''}" data-go="${m.id}"><i>${m.icon}</i>${m.name}</button>`}).join('');document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function go(id){current=id;editIndex=null;menu();render();document.querySelector('.sidebar').classList.remove('open')}
function pageHeader(title,crumb='GESTÃO DA CLÍNICA'){document.querySelector('#pageTitle').textContent=title;document.querySelector('#crumb').textContent=crumb}
function initials(n='?'){return n.split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function dashboard(){pageHeader('Olá, equipe!','VISÃO GERAL');const d=db(), a=d.agendamentos||[];return `<div class="cards"><div class="card"><div class="metric-label">CONSULTAS HOJE</div><div class="metric">${a.length||0}</div><div class="metric-trend">↑ Agenda ativa</div></div><div class="card"><div class="metric-label">PACIENTES ATIVOS</div><div class="metric">${(d.pacientes||[]).length}</div><div class="metric-trend">↑ Base atualizada</div></div><div class="card"><div class="metric-label">RECEITAS DO MÊS</div><div class="metric">R$ 1,7k</div><div class="metric-trend">↑ Registros lançados</div></div><div class="card"><div class="metric-label">ESTOQUE BAIXO</div><div class="metric">1</div><div class="metric-trend" style="color:#cb7c1d">Atenção necessária</div></div></div><div class="two-col"><div class="panel"><div class="panel-head"><h2>Agenda de hoje</h2><button class="btn secondary" onclick="go('agendamentos')">Ver agenda</button></div>${a.slice(0,5).map(x=>`<div class="list-row"><div class="circle">${initials(x[0])}</div><div class="row-main"><strong>${x[0]}</strong><small>${x[1]} · ${x[2]} às ${x[3]}</small></div><span class="badge ${String(x[4]).toLowerCase()}">${x[4]||'Agendado'}</span></div>`).join('')||'<p>Nenhum agendamento registrado.</p>'}</div><div class="panel"><div class="panel-head"><h2>Atalhos</h2></div><p>Crie rapidamente um novo registro.</p><button class="btn" onclick="go('agendamentos')">+ Agendar consulta</button><br><br><button class="btn secondary" onclick="go('pacientes')">+ Cadastrar paciente</button></div></div>`}
function generic(m){pageHeader(label(m));const rows=(db()[m.id]||[]), fields=m.fields;return `<div class="panel"><div class="toolbar"><input class="search" placeholder="Pesquisar registros..." oninput="filterRows(this.value)"><button class="btn" onclick="openForm()">+ Novo registro</button></div><div id="tableWrap">${table(rows,fields)}</div></div>`}
function table(rows,fields){if(!rows.length)return '<div class="empty">Nenhum registro encontrado. Clique em “Novo registro” para começar.</div>';return `<table><thead><tr>${fields.map(f=>`<th>${f.toUpperCase()}</th>`).join('')}<th>AÇÕES</th></tr></thead><tbody>${rows.map((r,i)=>`<tr>${fields.map((f,j)=>`<td>${r[j]||'—'}</td>`).join('')}<td class="actions"><button class="icon-btn" onclick="editRow(${i})" title="Editar">✎</button><button class="icon-btn" onclick="deleteRow(${i})" title="Excluir">⌫</button></td></tr>`).join('')}</tbody></table>`}
function filterRows(q){const m=modules.find(x=>x.id===current),rows=(db()[current]||[]).filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase()));document.querySelector('#tableWrap').innerHTML=table(rows,m.fields)}
function openForm(row=null,i=null){const m=modules.find(x=>x.id===current);editIndex=i;document.querySelector('#content').innerHTML=`<div class="panel"><div class="panel-head"><h2>${row?'Editar':'Novo'} registro — ${m.name}</h2><button class="btn secondary" onclick="render()">Voltar</button></div><form onsubmit="submitForm(event)"><div class="form-grid">${m.fields.map((f,j)=>`<div class="field ${f.includes('Observações')||f.includes('Registro')?'full':''}"><label>${f}</label>${f.includes('Observações')||f.includes('Registro')?`<textarea name="f${j}" rows="4" required>${row?.[j]||''}</textarea>`:`<input name="f${j}" value="${row?.[j]||''}" required>`}</div>`).join('')}</div><div class="form-actions"><button type="button" class="btn secondary" onclick="render()">Cancelar</button><button class="btn">Salvar registro</button></div></form></div>`}
function submitForm(e){e.preventDefault();const d=db(),vals=[...new FormData(e.target).values()].map(v=>v.trim());d[current]??=[];if(editIndex===null)d[current].push(vals);else d[current][editIndex]=vals;save(d);toast('Registro salvo com sucesso.');render()}
function editRow(i){openForm(db()[current][i],i)}function deleteRow(i){if(confirm('Excluir este registro?')){const d=db();d[current].splice(i,1);save(d);toast('Registro excluído.');render()}}
function finance(){pageHeader('Relatório financeiro','FINANCEIRO');const d=db(),sum=k=>(d[k]||[]).reduce((s,x)=>s+(parseFloat(String(x[2]).replace('.','').replace(',','.'))||0),0),rec=sum('receitas'),des=sum('despesas');return `<div class="stat-grid"><div class="stat"><small>RECEITAS</small><strong>R$ ${rec.toLocaleString('pt-BR',{minimumFractionDigits:2})}</strong></div><div class="stat"><small>DESPESAS</small><strong>R$ ${des.toLocaleString('pt-BR',{minimumFractionDigits:2})}</strong></div><div class="stat"><small>SALDO</small><strong>R$ ${(rec-des).toLocaleString('pt-BR',{minimumFractionDigits:2})}</strong></div></div><div class="panel"><div class="panel-head"><h2>Fluxo financeiro mensal</h2><button class="btn secondary" onclick="window.print()">Imprimir relatório</button></div><div class="chart">${[42,60,35,75,53,87,66].map((n,i)=>`<div class="bar ${i===5?'highlight':''}" style="height:${n}%"><span>${['Jan','Fev','Mar','Abr','Mai','Jun','Jul'][i]}</span></div>`).join('')}</div></div>`}
function indicators(){pageHeader('Indicadores da clínica','ANÁLISES');const d=db();return `<div class="cards"><div class="card"><div class="metric-label">TAXA DE PRESENÇA</div><div class="metric">87%</div><div class="metric-trend">↑ +4% este mês</div></div><div class="card"><div class="metric-label">NOVOS PACIENTES</div><div class="metric">${(d.pacientes||[]).length}</div><div class="metric-trend">Cadastros no sistema</div></div><div class="card"><div class="metric-label">TICKET MÉDIO</div><div class="metric">R$ 150</div><div class="metric-trend">Por sessão</div></div><div class="card"><div class="metric-label">OCUPAÇÃO</div><div class="metric">72%</div><div class="metric-trend">Das salas disponíveis</div></div></div><div class="panel"><h2>Como usar estes indicadores</h2><p>Utilize estes dados para discutir cenários de teste: cálculo, dados vazios, permissões de visualização, acessibilidade e responsividade.</p></div>`}
function render(){const m=modules.find(x=>x.id===current);document.querySelector('#content').innerHTML=current==='dashboard'?dashboard():current==='relatorio'?finance():current==='indicadores'?indicators():generic(m)}
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
document.querySelector('#seedBtn').onclick=()=>{if(confirm('Restaurar os dados de exemplo? Os registros atuais serão substituídos.')){localStorage.removeItem('menteSerenaDB');seed();render();toast('Dados de exemplo restaurados.')}};document.querySelector('#mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelector('#today').textContent=new Intl.DateTimeFormat('pt-BR',{dateStyle:'long'}).format(new Date());seed();menu();render();
